
version: '3'

services:
    app:
        build: .
        volumes:
            - ./loader/data:/loader/loader/data
        links:
          - db
        environment:
            - DATABASE_HOST: db
            - SCHEDULE_MINUTES_INTERVAL

    db:
        image: "postgres:latest"
        ports:
            - "5432:5432"
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql

