
version: '3'

services:
    app:
        build: .
        volumes:
            - ./loader/data:/loader/data
        depends_on:
          - db

    db:
        image: "postgres:latest"
        ports:
            - "5432:5432"
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data

