
version: '3'

services:
    app:
        build: .
        volumes:
            - ${LOADER_DATA_PATH}:/loader/loader/data
        links:
          - db
        environment:
            DATABASE_HOST: db

    db:
        image: "postgres:latest"
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
            - ${DATABASE_DATA_PATH}:/var/lib/postgresql/data
